version: "3.7"

services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=ronnie01
      - MYSQL_DATABASE=testdb
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - spring-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-mysql-network: